name: Deploy Website

on:
  push:
    branches: [main]
    paths:
      - 'web_visualizer/**'  # Only run when web/ changes

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./web_visualizer
          publish_branch: gh-pages
